### ISSUE TITLE
Add Sync/Delete option

### ISSUE THREAD

**Issue by AMeng** [trueaccord/DogPush#8]
I see in the docs that the `push` command:

> will never remove or touch untracked monitors (that is, datadog monitors that are not any of the yaml files).

However, it would be nice to keep monitors completely in sync with my YAML configs, even if that means deleting monitors.

Something like `dogpush sync` which does push/delete, or a flag on the push command like `--delete` to enable this option.

I would be glad to work on this if you think its an acceptable feature.

**Comment by thesamet** [comment]
Yes, this feature makes sense. Feel free to send a PR.
